{% set pyproject = load_file_data('pyproject.toml') %}
{% set version = pyproject.get('project').get('version') %}

channels:
  - conda-forge
  - defaults  
channel_priority: strict

package:
  name: cratermaker
  version: "{{ version }}"

source:
  path: ..  

build:
  script: |
    {{ PYTHON }} -m pip install . --no-deps -vv
  number: 0

requirements:
  host:
    - python>=3.10
    - numpy
    - scikit-build-core
    - cython
    - cmake
    - ninja
    - jinja2
    - setuptools
    - setuptools_scm
  run:
    - numpy
    - xarray>=2024.10.0
    - uxarray>=2024.10.1
    - scipy
    - pandas
    - matplotlib
    - vtk
    - jigsaw
    - jigsawpy
    - mpas_tools
    - tqdm
test:
  imports:
    - cratermaker  
  requires:
    - pytest

about:
  home: https://cratermaker.readthedocs.io
  license: GPL-3.0-or-later  
  summary: "A package for simulating crater formation on planetary bodies"  
  license_file: LICENSE  

extra:
  recipe-maintainers:
    - profminton 
