# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build documentation with Sphinx
sphinx:
  configuration: docs/conf.py
  fail_on_warning: false  # Optional: Set to true if you want the build to fail on warnings.

build:
  os: ubuntu-22.04
  tools:
    python: "mambaforge-22.9"  
  apt_packages:
    - graphviz    
  jobs:
    post_create_environment: 
      - pip install .
      - ford fortran_docs.md 

conda:
  environment: docs/environment.yml
