# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

 install:
    - requirements: docs/requirements.txt


# Build documentation with Sphinx
sphinx:
  configuration: docs/conf.py
  fail_on_warning: false  

python:
  install:
    - requirements: environments/requirements-docdev.txt

build:
  os: ubuntu-22.04
  tools:
    python: "3.13"
    rust: "latest"
  apt_packages:
    - pandoc
    - libssl-dev
    - libopenblas-dev
  jobs:
    post_create_environment: 
      - git fetch --prune --unshallow
      - git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - python buildscripts/set_version.py
      - pip install .

