name: build_cratermaker_ubuntu_arm

on:
  workflow_dispatch:
  push:
    branches:
      - 64-add-aarch64-wheel-build-to-github-actions 

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04-arm]

    steps:
      - uses: actions/checkout@v4

      - name: Get history and tags for SCM versioning to work
        run: |
          git fetch --prune --unshallow
          git fetch --depth=1 origin +refs/tags/*:refs/tags/*

      - uses: actions/setup-python@v5
        with:
          python-version: '>=3.10'

      - name: Set version
        shell: bash
        run: |
          python buildscripts/set_version.py

      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          target: ${{ matrix.platform.target }}
          args: --release --out dist --find-interpreter
          sccache: ${{ !startsWith(github.ref, 'refs/tags/') }}
          manylinux: auto

      - name: pytest
        shell: bash
        run: |
          set -e
          python3 -m venv .venv
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            source .venv/Scripts/activate
          else
            source .venv/bin/activate
          fi
          pip install cratermaker --find-links dist --force-reinstall
          pip install pytest
          pytest

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: dist/*.whl
          retention-days: 1



